

public enum TipoMensaje {
	ENVIARFICHERO, 
	//OC
	CONEXION, PEDIRLISTA, CERRARCONEXION, PEDIRFICHERO, PREPARADOCS,
	//OS
	CONFCONEXION, CONFPEDIRLISTA, CONFCERRAR,PREPARADOSC,EMITIRF, 
	CONFFICHERO,PEDIRFICHEROC,
	CONFDESCARGA, ERROR
}
